#!/usr/bin/expect

spawn -noecho {*}$argv

set timeout 5
expect {
  "(yes/no)" {
    send "yes\n"
    exp_continue
  }
  -re "\[Pp]ass(word|phrase)" {
    set pass $env(LOGIN_PASSWORD)
    send -- "$pass\n"
    set timeout 1
    exp_continue
  }
  "login" {
    interact
  }
  timeout {
   if {[catch { system {[[ -t 0 ]]} } error]} {
      while {[gets stdin line] != -1} {
        send "$line\n"
      }
      send \004
      log_user 0
      expect {
        -ex ^D {}
        -timeout 5 timeout { exit 1 }
      }
      log_user 1
      expect {
        eof {}
        -timeout 600 timeout { exit 1 }
      }
    }
  }
}

catch wait rc
exit [lindex $rc 3]

