#!/usr/bin/expect

set timeout 300

spawn bash -c "[join $argv]"

expect {
  -re "\pass(word|phrase)" {
    set pass $env(LOGIN_PASSWORD)
    send -- "$pass\n"
    exp_continue
  }
  "yes/no" {
    send "yes\n"
    exp_continue
  }
  "login" {
    interact
  }
  timeout {
    send_error "expect timed out\n"
    exit 1
  }
}

catch wait rc
exit [lindex $rc 3]

